### ISSUE TITLE
Error loading signatures when used via `rbs collection install` and `steep check`

### ISSUE THREAD

**Issue by HoneyryderChuck** [DataDog/datadog-ci-rb#111]
**Current behaviour**

When using datadog using rbs, I'm getting errors from loading datadog's signatures:

```
../../.gem/ruby/3.2.2/gems/datadog-ci-0.6.0/sig/datadog/ci/test_visibility/flush.rbs:11:8: [error] Cannot find type `Tracing::Flush::Partial`
│ Diagnostic ID: RBS::UnknownTypeName
│
└         class Partial < Tracing::Flush::Partial
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../.gem/ruby/3.2.2/gems/datadog-ci-0.6.0/sig/datadog/ci/contrib/rspec/runner.rbs:9:12: [error] Cannot find type `::RSpec::Core::Runner`
│ Diagnostic ID: RBS::UnknownTypeName
│
└             include ::RSpec::Core::Runner
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../.gem/ruby/3.2.2/gems/datadog-ci-0.6.0/sig/datadog/ci/configuration/components.rbs:4:26: [error] Cannot find type `Datadog::Core::Configuration::Components`
│ Diagnostic ID: RBS::UnknownTypeName
│
└       module Components : Datadog::Core::Configuration::Components
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# and so on
```
These signatures shouldn't IMO be loaded for projects using datadog, as they seem to be related to datadog CI environment.

**Expected behaviour**

I shouldn't get such errors.

This could be achievable by renaming the directory to `_ci`, which would make other projects not load it.

**Comment by anmarchenko** [comment]
Hi! Thanks a lot for you bug report, indeed these are errors from vendored dependencies that are not published as part of this gem.

I should remove `sig` folder from the library altogether and will do before the next release. In the meantime feel free to ignore this folder in your Steepfile, sorry for the inconvenience.
