### ISSUE TITLE
Ability to disable ITR/test optimization GHA annotations

### ISSUE THREAD

**Issue by sulami** [DataDog/datadog-ci-rb#266]
**Is your feature request related to a problem? Please describe.**

We have a suite of ~33k tests, and recently have been trying test optimization. It skips tests as described, but adds an annotation on the GitHub Actions job/workflow to the test, saying that it skipped the test. This means we now have tens of thousands of annotations on every workflow, drowning out potentially actionable annotations from others sources. It would be nice to turn off those annotations, or maybe collapse them down into a single "some tests have been skipped by Datadog" annotation.

**Describe the goal of the feature**

Reduce the number of unactionable annotations on GHA workflows due to intelligent test skipping.

**Describe alternatives you've considered**

None really, outside of living with it. It's not a deal breaker for us, just a bit annoying.

**Additional context**

Example:

![Image](https://github.com/user-attachments/assets/22de6084-a4c4-40b8-b046-09a0a58f2a16)

**How does `datadog-ci` help you?**

Identification and automatic re-trying of flaky tests has been a savior for us. The feature formerly known as ITR looks promising to save us a lot of money currently spent on CI runners.

**Comment by anmarchenko** [comment]
Hi @sulami! Thanks for contacting us. 

These annotations don't come from Datadog, they are emitted by Github Actions. The comments from Datadog always emitted by Datadog GH app that you install in your GH account. And we never post so many comments about such a trivial thing as test skipped by intelligent test runner 😅 

I would guess that you have some kind of Github Actions integration in your test suite that posts a comment for every skipped test in your test suite. Could you check that?

**Comment by anmarchenko** [comment]
For the context, on this page you can see a screenshot of how Datadog's GitHub integration looks like: it is a single comment in your PR with a summary of everything that was run and skipped:

https://docs.datadoghq.com/tests/developer_workflows

**Comment by sulami** [comment]
Ah, that makes a lot more sense, and at least validates my questioning of this as a design decision 😅

Looking through our code, I suspect these annotations are coming from https://github.com/Drieam/rspec-github, which I'll have to wrangle instead to get rid of those annotations.

Closing this then, have a good day!
